apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ledger
labels:
  - pairs: {app.kubernetes.io/part-of: ledger-core}
    includeSelectors: false
resources:
  - namespace.yaml
  - config.yaml
  - networkpolicy.yaml
  - accounts.yaml
  - transfers.yaml
  - gateway.yaml
  - notifications.yaml
  - reconciler.yaml
