apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ledger
resources:
  - jobs.yaml
images:
  - {name: ghcr.io/igormirkhanov/ledger-core-accounts, newTag: latest}
  - {name: ghcr.io/igormirkhanov/ledger-core-transfers, newTag: latest}
  - {name: ghcr.io/igormirkhanov/ledger-core-notifications, newTag: latest}
